version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-template-lint
    versions:
    - 2.21.0
    - 3.0.0
    - 3.0.1
    - 3.1.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.5.0
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
  - dependency-name: ember-cli
    versions:
    - 3.25.1
  - dependency-name: "@clark/eslint-config-ember"
    versions:
    - 2.0.0
    - 2.1.0
