# This workflow is largely based on
# https://github.com/salsify/ember-css-modules/blob/master/.github/workflows/ci.yml

name: CI

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  workflow_dispatch:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master
      - "v*"
    # always run CI for tags
    tags:
      - "*"
  # early issue detection: run CI weekly on Sundays
  schedule:
    - cron: "0 6 * * 0"

env:
  CI: true

jobs:
  test-locked-deps:
    name: Locked Deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint JS
        run: yarn lint:js
      - name: Lint Handlebars
        run: yarn lint:hbs
      - name: Browser Tests
        run: yarn test

  test-old-dependencies:
    name: Oldest Supported Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Browser Tests
        run: yarn test

  test-try:
    name: Ember Try
    runs-on: ubuntu-latest
    needs: [test-locked-deps]
    strategy:
      matrix:
        scenario:
          - ember-2.13
          - ember-lts-2.18
          - ember-lts-3.4
          - ember-release
          - ember-beta
          - ember-canary
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Try Scenario
        run: yarn ember try:one ${{ matrix.scenario }}
